[package]
name = "exchange"
version = "0.18.3"
license = "MIT OR Apache-2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>"]
edition = "2018"

description = "Rust Library for the Binance-like API"
keywords = ["cryptocurrency", "trading", "exchange"]
categories = ["api-bindings", "cryptography::cryptocurrencies"]
documentation = "https://docs.rs/crate/binance/"
repository = "https://github.com/tqtensor/exchange-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "tqtensor/exchange-rs" }

[lib]
name = "exchange"
path = "src/lib.rs"

[dependencies]
hex = "0.4"
hmac = "0.12.0"
sha2 = "0.10"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
error-chain = { version = "0.12.4", default-features = false }
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
tungstenite = { version = "0.16.0", features = ["native-tls"] }
url = "2.2.2"

[features]
vendored-tls = [
    "reqwest/native-tls-vendored",
    "tungstenite/native-tls-vendored",
]

[dev-dependencies]
csv = "1.1.6"
mockito = "0.30.0"
env_logger = "0.9.0"
criterion = "0.3"
float-cmp = "0.9.0"
serde_json = "1.0"

[[bench]]
name = "websocket_benchmark"
harness = false
